import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';

interface AnalysisReport {
  executiveSummary: string;
  contractOverview: string;
  performanceMetrics: string;
  businessInsights: string;
  riskAssessment: string;
  recommendations: string;
  technicalAnalysis: string;
  marketPosition: string;
}

export class DocumentService {
  static async generateDocxReport(
    report: AnalysisReport, 
    contractAddress: string, 
    contractInfo: any,
    stats: any
  ): Promise<Blob> {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          // Title Page
          new Paragraph({
            children: [
              new TextRun({
                text: "STARKNET CONTRACT ANALYSIS REPORT",
                bold: true,
                size: 32,
                color: "2563eb"
              })
            ],
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 }
          }),
          
          new Paragraph({
            children: [
              new TextRun({
                text: `Contract: ${contractInfo.contractName || 'Smart Contract'}`,
                bold: true,
                size: 24
              })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 }
          }),
          
          new Paragraph({
            children: [
              new TextRun({
                text: `Address: ${contractAddress}`,
                size: 20,
                font: "Courier New"
              })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 }
          }),
          
          new Paragraph({
            children: [
              new TextRun({
                text: `Type: ${contractInfo.contractType}`,
                size: 18
              })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 }
          }),
          
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated: ${new Date().toLocaleDateString()}`,
                size: 16,
                italics: true
              })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 800 }
          }),

          // Key Metrics Summary
          new Paragraph({
            children: [
              new TextRun({
                text: "KEY METRICS OVERVIEW",
                bold: true,
                size: 20,
                color: "1f2937"
              })
            ],
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 }
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `• Total Events: ${stats.totalEvents}\n• Unique Users: ${stats.uniqueUsers}\n• Total Transactions: ${stats.totalTransactions}\n• Block Range: ${stats.dateRange.span} blocks\n• Activity Status: ${stats.isActive ? 'Active' : 'Low Activity'}`,
                size: 22
              })
            ],
            spacing: { after: 400 }
          }),

          // Executive Summary
          ...this.createSection("EXECUTIVE SUMMARY", report.executiveSummary),
          
          // Contract Overview
          ...this.createSection("CONTRACT OVERVIEW", report.contractOverview),
          
          // Performance Metrics
          ...this.createSection("PERFORMANCE METRICS", report.performanceMetrics),
          
          // Business Insights
          ...this.createSection("BUSINESS INSIGHTS", report.businessInsights),
          
          // Risk Assessment
          ...this.createSection("RISK ASSESSMENT", report.riskAssessment),
          
          // Technical Analysis
          ...this.createSection("TECHNICAL ANALYSIS", report.technicalAnalysis),
          
          // Market Position
          ...this.createSection("MARKET POSITION", report.marketPosition),
          
          // Recommendations
          ...this.createSection("STRATEGIC RECOMMENDATIONS", report.recommendations),

          // Footer
          new Paragraph({
            children: [
              new TextRun({
                text: "Generated by Starklytics Suite - Advanced Starknet Analytics Platform",
                size: 18,
                italics: true,
                color: "6b7280"
              })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 800, after: 200 }
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: "This report is generated using on-chain data analysis and AI-powered insights.",
                size: 16,
                italics: true,
                color: "9ca3af"
              })
            ],
            alignment: AlignmentType.CENTER
          })
        ]
      }]
    });

    return await Packer.toBlob(doc);
  }

  private static createSection(title: string, content: string): Paragraph[] {
    const paragraphs: Paragraph[] = [];
    
    // Section title
    paragraphs.push(new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 24,
          color: "1f2937"
        })
      ],
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 600, after: 300 }
    }));

    // Process content - split by paragraphs and format
    const sections = content.split('\n\n').filter(section => section.trim());
    
    sections.forEach(section => {
      const lines = section.split('\n').filter(line => line.trim());
      
      lines.forEach(line => {
        const trimmedLine = line.trim();
        if (!trimmedLine) return;

        let textRun: TextRun;
        let isHeading = false;

        // Format different types of content
        if (trimmedLine.startsWith('**') && trimmedLine.endsWith('**')) {
          // Bold headings
          textRun = new TextRun({
            text: trimmedLine.replace(/\*\*/g, ''),
            bold: true,
            size: 22,
            color: "374151"
          });
          isHeading = true;
        } else if (trimmedLine.startsWith('•')) {
          // Bullet points
          textRun = new TextRun({
            text: trimmedLine,
            size: 20
          });
        } else if (trimmedLine.includes(':') && trimmedLine.length < 100) {
          // Key-value pairs
          textRun = new TextRun({
            text: trimmedLine,
            size: 20,
            bold: trimmedLine.split(':')[0].length < 30
          });
        } else {
          // Regular text
          textRun = new TextRun({
            text: trimmedLine,
            size: 20
          });
        }

        paragraphs.push(new Paragraph({
          children: [textRun],
          spacing: { 
            before: isHeading ? 300 : 100, 
            after: isHeading ? 200 : 100 
          }
        }));
      });
    });

    return paragraphs;
  }

  static generateGoogleDocsLink(contractAddress: string, contractInfo: any, report?: any): string {
    // Create the report content
    const content = `STARKNET CONTRACT ANALYSIS REPORT

Contract: ${contractInfo.contractName || 'Smart Contract'}
Address: ${contractAddress}
Type: ${contractInfo.contractType}
Generated: ${new Date().toLocaleDateString()}

${report?.executiveSummary || ''}

${report?.contractOverview || ''}

${report?.performanceMetrics || ''}

${report?.businessInsights || ''}

${report?.riskAssessment || ''}

${report?.technicalAnalysis || ''}

${report?.marketPosition || ''}

${report?.recommendations || ''}

Generated by Starklytics Suite`;
    
    // Encode content for URL (truncate if too long to avoid URL limits)
    const maxLength = 8000; // Safe URL length limit
    const truncatedContent = content.length > maxLength ? content.substring(0, maxLength) + '\n\n[Content truncated due to length limits]' : content;
    const encodedContent = encodeURIComponent(truncatedContent);
    
    // Create Google Docs URL with pre-filled content
    const googleDocsUrl = `https://docs.google.com/document/create?title=${encodeURIComponent(contractInfo.contractName + ' Analysis Report')}&body=${encodedContent}`;
    
    return googleDocsUrl;
  }
}